# Generated by Django 5.2.4 on 2025-08-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvaluationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text_answer', models.TextField()),
                ('ai_response', models.CharField(blank=True, max_length=50)),
                ('is_correct_by_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_attempts', to='interview_app.question')),
            ],
        ),
    ]
