# Generated by Django 5.1.7 on 2025-08-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0002_aievaluationattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='complexity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
