# Generated by Django 5.1.7 on 2025-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0004_category_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aievaluationattempt',
            name='ai_response',
            field=models.TextField(blank=True),
        ),
    ]
